<?php
if(!defined('ABSPATH'))exit;
final class Faluss_Link_Admin {
 const OPTION='faluss_link_network_catalog';
 public static function defaults(){return array('instagram'=>array('label'=>'Instagram','active'=>1,'icon'=>0),'tiktok'=>array('label'=>'TikTok','active'=>1,'icon'=>0),'youtube'=>array('label'=>'YouTube','active'=>1,'icon'=>0),'x'=>array('label'=>'X','active'=>1,'icon'=>0),'linkedin'=>array('label'=>'LinkedIn','active'=>1,'icon'=>0),'github'=>array('label'=>'GitHub','active'=>1,'icon'=>0));}
 public static function catalog(){$saved=(array)get_option(self::OPTION,array());$catalog=array();foreach(self::defaults() as $slug=>$default)$catalog[$slug]=array_merge($default,(array)($saved[$slug]??array()));return $catalog;}
 public static function active_catalog(){return array_filter(self::catalog(),static function($network){return !empty($network['active']);});}
 public static function boot(){if(!is_admin())return;add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_post_faluss_link_save_networks',array(__CLASS__,'save'));add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));}
 public static function menu(){add_options_page('Réseaux Faluss Link','Réseaux Faluss Link','manage_options','faluss-link-networks',array(__CLASS__,'page'));}
 public static function assets($hook){if('settings_page_faluss-link-networks'!==$hook)return;wp_enqueue_media();wp_add_inline_script('media-editor','jQuery(function($){$(document).on("click",".faluss-link-icon-picker",function(e){e.preventDefault();var b=$(this),f=wp.media({title:"Icône du réseau",multiple:false,library:{type:"image"}});f.on("select",function(){b.siblings("input").val(f.state().get("selection").first().get("id"));});f.open();});});');}
 public static function save(){if(!current_user_can('manage_options')||!isset($_POST['faluss_link_networks_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['faluss_link_networks_nonce'])),'faluss_link_save_networks'))wp_die('Accès refusé.');$out=array();foreach(self::defaults() as $slug=>$default){$row=isset($_POST['networks'][$slug])?(array)wp_unslash($_POST['networks'][$slug]):array();$icon=max(0,(int)($row['icon']??0));$out[$slug]=array('label'=>sanitize_text_field($row['label']??$default['label'])?:$default['label'],'active'=>empty($row['active'])?0:1,'icon'=>$icon&&wp_attachment_is_image($icon)?$icon:0);}update_option(self::OPTION,$out,false);wp_safe_redirect(admin_url('options-general.php?page=faluss-link-networks&updated=1'));exit;}
 public static function page(){if(!current_user_can('manage_options'))return;$catalog=self::catalog();?><div class="wrap"><h1>Réseaux Faluss Link</h1><p>Les membres ne voient que les réseaux activés. Sans icône personnalisée, Faluss Link utilise son pictogramme intégré.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="faluss_link_save_networks"><?php wp_nonce_field('faluss_link_save_networks','faluss_link_networks_nonce'); ?><table class="widefat"><thead><tr><th>Réseau</th><th>Actif</th><th>Icône</th></tr></thead><tbody><?php foreach($catalog as $slug=>$network): ?><tr><td><input name="networks[<?php echo esc_attr($slug); ?>][label]" value="<?php echo esc_attr($network['label']); ?>"></td><td><input type="checkbox" name="networks[<?php echo esc_attr($slug); ?>][active]" value="1" <?php checked(!empty($network['active'])); ?>></td><td><input name="networks[<?php echo esc_attr($slug); ?>][icon]" value="<?php echo (int)$network['icon']; ?>" readonly> <button class="button faluss-link-icon-picker" type="button">Choisir</button></td></tr><?php endforeach; ?></tbody></table><?php submit_button('Enregistrer les réseaux'); ?></form></div><?php }
}
