<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Faluss_Link {
 const STYLE='faluss-link-card', SCRIPT='faluss-link-editor';
 const NETWORKS=array('instagram','tiktok','youtube','x','linkedin','github');
 const ANNOUNCEMENTS=array('accent'=>'Accent / ink','ink'=>'Ink / white');
 const NAME_TREATMENTS=array('editorial'=>'Éditorial','strong'=>'Fort');
 const LAYOUTS=array('bubbles'=>'Bulles','inline'=>'Ligne');
 const LINK_STYLES=array('solid'=>'Plein','outline'=>'Contour');
 public static function boot(){add_shortcode('faluss_link_card',array(__CLASS__,'card_shortcode'));add_shortcode('faluss_link_appearance',array(__CLASS__,'appearance_shortcode'));add_shortcode('faluss_link_studio',array(__CLASS__,'studio_shortcode'));add_action('admin_post_faluss_link_save',array(__CLASS__,'save'));add_action('wp_ajax_faluss_link_upload_cover',array(__CLASS__,'upload_cover'));add_action('wp_enqueue_scripts',array(__CLASS__,'assets'));add_action('elementor/widgets/register',array(__CLASS__,'widgets'));}
 public static function activate(){return Faluss_Link_Schema::install();}
 public static function assets(){wp_register_style(self::STYLE,plugins_url('assets/css/faluss-link.css',FALUSS_LINK_FILE),array(),FALUSS_LINK_VERSION);wp_register_script(self::SCRIPT,plugins_url('assets/js/faluss-link-editor.js',FALUSS_LINK_FILE),array('jquery'),FALUSS_LINK_VERSION,true);}
 public static function card_shortcode($a=array()){return self::render_card((array)$a);}
 public static function appearance_shortcode(){return self::render_editor();}
 public static function studio_shortcode(){return self::render_studio();}
 public static function render_card($a=array()){
  if(!self::identity_ready())return self::empty_card(__('Carte Faluss indisponible.','faluss-link'));
  $a=wp_parse_args($a,array('identifier'=>'','align'=>'center'));$slug=''!==$a['identifier']?sanitize_title($a['identifier']):(string)get_query_var('faluss_public_profile');$p=self::identity_profile($slug);if(!is_array($p))return self::empty_card(__('Cette carte Faluss n’est pas disponible.','faluss-link'));
  self::enqueue_assets();$pref=self::prefs($p['faluss_id']);$links=json_decode($p['external_links'],true);$social=self::socials($pref['social_links']);$has_cover=(int)$pref['cover_attachment_id']>0;$has_avatar=(int)$pref['avatar_visible']&&(int)$p['avatar_attachment_id']>0;
  ob_start(); ?><article class="faluss-link-card faluss-link-card--align-<?php echo esc_attr(in_array($a['align'],array('left','center','right'),true)?$a['align']:'center'); ?> faluss-link-card--links-<?php echo esc_attr($pref['link_style']); ?> faluss-link-card--cover-<?php echo $has_cover?'yes':'no'; ?> faluss-link-card--avatar-<?php echo $has_avatar?'yes':'no'; ?>" aria-label="<?php echo esc_attr($p['display_name']); ?>">
   <?php if($has_cover): ?><div class="faluss-link-card__cover"><?php echo wp_get_attachment_image((int)$pref['cover_attachment_id'],'large',false,array('alt'=>'')); ?></div><?php endif; ?>
   <div class="faluss-link-card__body"><?php if((int)$pref['available']): ?><span class="faluss-link-card__availability"><i></i><?php esc_html_e('Disponible','faluss-link'); ?></span><?php endif; ?>
   <?php if($has_avatar): ?><div class="faluss-link-card__avatar"><?php echo wp_get_attachment_image((int)$p['avatar_attachment_id'],'medium',false,array('alt'=>'')); ?></div><?php endif; ?>
   <h1 class="faluss-link-card__name faluss-link-card__name--<?php echo esc_attr($pref['name_treatment']); ?>"><?php echo esc_html($p['display_name']); ?></h1>
   <p class="faluss-link-card__handle">@<?php echo esc_html($p['public_slug']); ?></p>
   <?php if('announcement'===$pref['bio_mode']&&''!==$pref['announcement']): ?><p class="faluss-link-card__announcement faluss-link-card__announcement--<?php echo esc_attr($pref['announcement_variant']); ?>"><?php echo esc_html($pref['announcement']); ?></p><?php elseif(''!==$p['bio']): ?><p class="faluss-link-card__bio"><?php echo esc_html($p['bio']); ?></p><?php endif; ?>
   <?php if($social): ?><nav class="faluss-link-card__social faluss-link-card__social--<?php echo esc_attr($pref['social_layout']); ?>" aria-label="<?php esc_attr_e('Réseaux sociaux','faluss-link'); ?>"><?php foreach($social as $s): ?><a href="<?php echo esc_url($s['url']); ?>" target="_blank" rel="noopener noreferrer nofollow" aria-label="<?php echo esc_attr(ucfirst($s['network'])); ?>"><?php echo self::icon($s['network']); ?></a><?php endforeach; ?></nav><?php endif; ?>
   <?php foreach(is_array($links)?$links:array() as $l): if(!empty($l['url'])): ?><a class="faluss-link-card__link" href="<?php echo esc_url($l['url']); ?>" target="_blank" rel="noopener noreferrer nofollow"><?php echo esc_html($l['label']??$l['url']); ?></a><?php endif; endforeach; ?></div></article><?php return (string)ob_get_clean();
 }
 public static function render_editor(){
  if(!is_user_logged_in()||!self::identity_ready())return self::empty_card(__('Connectez-vous pour personnaliser votre carte.','faluss-link'));
  $id=Faluss_Identity_Registry::get_active_for_wp_user(get_current_user_id());if(!$id)return self::empty_card(__('Votre identité Faluss est indisponible.','faluss-link'));self::enqueue_assets();wp_enqueue_script(self::SCRIPT);wp_localize_script(self::SCRIPT,'falussLinkCover',array('url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('faluss_link_upload_cover')));$p=self::prefs($id);if((int)$p['cover_attachment_id']&&!self::owned_image((int)$p['cover_attachment_id'],get_current_user_id()))$p['cover_attachment_id']=0;$social=self::socials($p['social_links']);
  ob_start(); ?><section class="faluss-link-editor"><h2><?php esc_html_e('Apparence de ma carte Faluss','faluss-link'); ?></h2><?php echo self::link_notice(); ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="faluss_link_save"><?php wp_nonce_field('faluss_link_save','faluss_link_nonce'); ?>
  <div class="faluss-link-editor__media"><label><?php esc_html_e('Photo de couverture','faluss-link'); ?></label><input class="faluss-link-editor__cover-id" name="cover_attachment_id" type="hidden" value="<?php echo (int)$p['cover_attachment_id']; ?>"><button class="faluss-link-editor__select-cover" type="button"><?php esc_html_e('Choisir une image','faluss-link'); ?></button><button class="faluss-link-editor__remove-cover" type="button"><?php esc_html_e('Retirer','faluss-link'); ?></button><div class="faluss-link-editor__cover-preview"><?php if((int)$p['cover_attachment_id'])echo wp_get_attachment_image((int)$p['cover_attachment_id'],'medium',false,array('alt'=>'')); ?></div></div>
  <label><input name="avatar_visible" type="checkbox" value="1" <?php checked($p['avatar_visible']); ?>> <?php esc_html_e('Afficher l’avatar','faluss-link'); ?></label><label><input name="available" type="checkbox" value="1" <?php checked($p['available']); ?>> <?php esc_html_e('Afficher Disponible','faluss-link'); ?></label>
  <label><?php esc_html_e('Traitement du nom','faluss-link'); ?><select name="name_treatment"><?php foreach(self::NAME_TREATMENTS as $k=>$v): ?><option value="<?php echo esc_attr($k); ?>" <?php selected($p['name_treatment'],$k); ?>><?php echo esc_html($v); ?></option><?php endforeach; ?></select></label>
  <label><?php esc_html_e('Bio','faluss-link'); ?><select name="bio_mode"><option value="editorial" <?php selected($p['bio_mode'],'editorial'); ?>><?php esc_html_e('Texte éditorial','faluss-link'); ?></option><option value="announcement" <?php selected($p['bio_mode'],'announcement'); ?>><?php esc_html_e('Annonce','faluss-link'); ?></option></select></label><label><?php esc_html_e('Texte de l’annonce','faluss-link'); ?><input name="announcement" maxlength="120" value="<?php echo esc_attr($p['announcement']); ?>"></label><label><?php esc_html_e('Couleur de l’annonce','faluss-link'); ?><select name="announcement_variant"><?php foreach(self::ANNOUNCEMENTS as $k=>$v): ?><option value="<?php echo esc_attr($k); ?>" <?php selected($p['announcement_variant'],$k); ?>><?php echo esc_html($v); ?></option><?php endforeach; ?></select></label>
  <label><?php esc_html_e('Réseaux (réseau|URL HTTPS, un par ligne)','faluss-link'); ?><textarea name="social_links"><?php foreach($social as $s)echo esc_textarea($s['network'].'|'.$s['url'])."\n"; ?></textarea></label><label><?php esc_html_e('Affichage des réseaux','faluss-link'); ?><select name="social_layout"><?php foreach(self::LAYOUTS as $k=>$v): ?><option value="<?php echo esc_attr($k); ?>" <?php selected($p['social_layout'],$k); ?>><?php echo esc_html($v); ?></option><?php endforeach; ?></select></label><label><?php esc_html_e('Boutons de liens','faluss-link'); ?><select name="link_style"><?php foreach(self::LINK_STYLES as $k=>$v): ?><option value="<?php echo esc_attr($k); ?>" <?php selected($p['link_style'],$k); ?>><?php echo esc_html($v); ?></option><?php endforeach; ?></select></label><button type="submit"><?php esc_html_e('Enregistrer','faluss-link'); ?></button></form></section><?php return (string)ob_get_clean();
 }
 public static function render_studio(){if(!is_user_logged_in()||!self::identity_ready()||!class_exists('Faluss_Identity_Public_Profile'))return self::empty_card(__('Connectez-vous pour ouvrir Studio Faluss.','faluss-link'));$id=Faluss_Identity_Registry::get_active_for_wp_user(get_current_user_id());$p=self::member_profile($id);if(!$p)return self::empty_card(__('Créez votre profil Faluss avant de le personnaliser.','faluss-link'));self::enqueue_assets();$preview=self::studio_preview($p);ob_start();?><section class="faluss-link-studio"><header><div><?php if((int)$p['avatar_attachment_id'])echo wp_get_attachment_image((int)$p['avatar_attachment_id'],'thumbnail',false,array('alt'=>'')); ?><strong><?php echo esc_html($p['display_name']); ?></strong><span>@<?php echo esc_html($p['public_slug']); ?></span></div><a href="<?php echo esc_url(home_url('/'.$p['public_slug'])); ?>"><?php esc_html_e('Voir mon Faluss','faluss-link'); ?></a></header><nav role="tablist"><button role="tab" aria-selected="true" data-fl-tab="profile">Profil</button><button role="tab" aria-selected="false" data-fl-tab="links">Liens</button><button role="tab" aria-selected="false" data-fl-tab="appearance">Apparence</button></nav><div class="faluss-link-studio__workspace"><?php echo Faluss_Identity_Public_Profile::render_studio_fields(); ?><div data-fl-panel="appearance" hidden><?php echo self::render_editor(); ?></div><aside class="faluss-link-studio__preview" aria-label="<?php esc_attr_e('Aperçu de ma carte Faluss','faluss-link'); ?>"><h2><?php esc_html_e('Aperçu','faluss-link'); ?></h2><?php echo $preview; ?></aside></div></section><?php return (string)ob_get_clean();}
 public static function save(){if(!is_user_logged_in()||!isset($_POST['faluss_link_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['faluss_link_nonce'])),'faluss_link_save'))wp_die('Accès refusé.');$id=Faluss_Identity_Registry::get_active_for_wp_user(get_current_user_id());if(!$id)wp_die('Identité indisponible.');global $wpdb;$t=Faluss_Link_Schema::table();$pick=fn($v,$allowed,$default)=>in_array($v,$allowed,true)?$v:$default;$cover=max(0,(int)($_POST['cover_attachment_id']??0));if($cover&&!self::owned_image($cover,get_current_user_id()))$cover=0;$v=array('cover_attachment_id'=>$cover,'avatar_visible'=>!empty($_POST['avatar_visible'])?1:0,'name_weight'=>'bold','name_treatment'=>$pick(wp_unslash($_POST['name_treatment']??''),array_keys(self::NAME_TREATMENTS),'strong'),'available'=>!empty($_POST['available'])?1:0,'bio_mode'=>$pick(wp_unslash($_POST['bio_mode']??''),array('editorial','announcement'),'editorial'),'announcement'=>sanitize_text_field(wp_unslash($_POST['announcement']??'')),'announcement_variant'=>$pick(wp_unslash($_POST['announcement_variant']??''),array_keys(self::ANNOUNCEMENTS),'accent'),'social_links'=>wp_json_encode(self::socials(wp_unslash($_POST['social_links']??''))),'social_layout'=>$pick(wp_unslash($_POST['social_layout']??''),array_keys(self::LAYOUTS),'bubbles'),'link_style'=>$pick(wp_unslash($_POST['link_style']??''),array_keys(self::LINK_STYLES),'solid'));$now=gmdate('Y-m-d H:i:s');$old=self::prefs($id);$saved=$old['faluss_id']!==$id?$wpdb->query($wpdb->prepare('INSERT INTO `'.$t.'` (faluss_id,cover_attachment_id,avatar_visible,name_weight,name_treatment,available,bio_mode,announcement,announcement_variant,social_links,social_layout,link_style,created_at,updated_at) VALUES (%s,%d,%d,%s,%s,%d,%s,%s,%s,%s,%s,%s,%s,%s)',...array_merge(array($id),array_values($v),array($now,$now)))):$wpdb->update($t,$v+array('updated_at'=>$now),array('faluss_id'=>$id));$url=wp_validate_redirect(wp_get_referer(),home_url('/'));wp_safe_redirect(add_query_arg('faluss_link_notice',false===$saved?'invalid':'saved',$url));exit;}
 public static function upload_cover(){if(!is_user_logged_in()||!check_ajax_referer('faluss_link_upload_cover','nonce',false)||!self::identity_ready()||!Faluss_Identity_Registry::get_active_for_wp_user(get_current_user_id()))wp_send_json_error(array('message'=>'Accès refusé.'),403);if(empty($_FILES['cover'])||!is_array($_FILES['cover']))wp_send_json_error(array('message'=>'Image requise.'),400);require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/image.php';$file=$_FILES['cover'];$type=wp_check_filetype_and_ext($file['tmp_name'],$file['name']);if(empty($type['type'])||0!==strpos($type['type'],'image/'))wp_send_json_error(array('message'=>'Image invalide.'),400);$upload=wp_handle_upload($file,array('test_form'=>false,'mimes'=>array('jpg|jpeg|jpe'=>'image/jpeg','png'=>'image/png','gif'=>'image/gif','webp'=>'image/webp')));if(!empty($upload['error']))wp_send_json_error(array('message'=>'Envoi impossible.'),400);$attachment=array('post_mime_type'=>$upload['type'],'post_title'=>sanitize_file_name(pathinfo($upload['file'],PATHINFO_FILENAME)),'post_status'=>'inherit','post_author'=>get_current_user_id());$id=wp_insert_attachment($attachment,$upload['file']);if(is_wp_error($id)||!self::owned_image((int)$id,get_current_user_id()))wp_send_json_error(array('message'=>'Image invalide.'),400);wp_update_attachment_metadata($id,wp_generate_attachment_metadata($id,$upload['file']));wp_send_json_success(array('id'=>(int)$id,'url'=>wp_get_attachment_image_url($id,'medium')));}
 public static function widgets($m){if(!class_exists('Elementor\\Widget_Base')||!is_object($m)||!method_exists($m,'register'))return;require_once FALUSS_LINK_DIR.'includes/class-faluss-link-widgets.php';$m->register(new Faluss_Link_Card_Widget());$m->register(new Faluss_Link_Appearance_Widget());$m->register(new Faluss_Link_Studio_Widget());}
 public static function socials($value){$decoded=is_string($value)?json_decode($value,true):null;$in=is_array($decoded)?$decoded:(is_string($value)?preg_split('/\r\n|\r|\n/',$value):$value);$out=array();$seen=array();foreach((array)$in as $item){if(is_array($item)){$n=$item['network']??'';$u=$item['url']??'';}else{[$n,$u]=array_pad(explode('|',(string)$item,2),2,'');}$n=strtolower(trim((string)$n));$u=trim((string)$u);$parts=wp_parse_url($u);if(!in_array($n,self::NETWORKS,true)||!filter_var($u,FILTER_VALIDATE_URL)||!is_array($parts)||'https'!==strtolower($parts['scheme']??'')||isset($seen[$n.'|'.$u]))continue;$seen[$n.'|'.$u]=true;$out[]=array('network'=>$n,'url'=>$u);}return $out;}
 private static function identity_ready(){return class_exists('Faluss_Identity_Schema')&&class_exists('Faluss_Identity_Registry')&&!empty(Faluss_Identity_Schema::get_status()['ready']);}
 private static function identity_profile($slug){global $wpdb;if(!is_string($slug)||''===$slug)return null;$t=Faluss_Identity_Schema::get_public_profiles_table();return $wpdb->get_row($wpdb->prepare('SELECT faluss_id,public_slug,display_name,bio,avatar_attachment_id,external_links FROM `'.$t.'` WHERE public_slug=%s AND publication_status=%s',$slug,'published'),ARRAY_A);}
 private static function member_profile($id){global $wpdb;$t=Faluss_Identity_Schema::get_public_profiles_table();return $wpdb->get_row($wpdb->prepare('SELECT faluss_id,public_slug,display_name,bio,avatar_attachment_id FROM `'.$t.'` WHERE faluss_id=%s',$id),ARRAY_A);}
 private static function prefs($id){global $wpdb;$d=array('faluss_id'=>'','cover_attachment_id'=>0,'avatar_visible'=>1,'name_weight'=>'bold','name_treatment'=>'strong','available'=>0,'bio_mode'=>'editorial','announcement'=>'','announcement_variant'=>'accent','social_links'=>'[]','social_layout'=>'bubbles','link_style'=>'solid');$r=$wpdb->get_row($wpdb->prepare('SELECT * FROM `'.Faluss_Link_Schema::table().'` WHERE faluss_id=%s',$id),ARRAY_A);return is_array($r)?array_merge($d,$r):$d;}
 private static function icon($n){$paths=array('instagram'=>'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/>','tiktok'=>'<path d="M14 4v10.5a4 4 0 1 1-3-3.87"/><path d="M14 4c1 2.4 2.7 3.8 5 4"/>','youtube'=>'<path fill="currentColor" stroke="none" d="M21 12s0-4-1-5-7-1-8-1-7 0-8 1-1 5-1 5 0 4 1 5 7 1 8 1 7 0 8-1 1-5 1-5z"/><path fill="#FFFDF5" stroke="none" d="m10 9 5 3-5 3z"/>','x'=>'<path d="M5 4l14 16M19 4 5 20"/>','linkedin'=>'<path d="M6 9v9M6 6v.1M10 18v-5a3 3 0 0 1 6 0v5M10 12V9"/>','github'=>'<path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.9c0-1.1.1-1.8-.5-2.5 2-.2 4-1 4-4.5 0-1-.3-1.8-.8-2.5.1-.2.4-1.2-.1-2.5 0 0-.7-.2-2.5 1a8.6 8.6 0 0 0-4.5 0c-1.8-1.2-2.5-1-2.5-1-.5 1.3-.2 2.3-.1 2.5-.5.7-.8 1.5-.8 2.5 0 3.5 2 4.3 4 4.5-.4.4-.6 1-.6 2v3.9"/>');return '<svg aria-hidden="true" viewBox="0 0 24 24">'.$paths[$n].'</svg>';}
 private static function enqueue_assets(){if(!wp_style_is(self::STYLE,'registered'))self::assets();wp_enqueue_style(self::STYLE);}
 private static function studio_preview($p){$preview=self::render_card(array('identifier'=>$p['public_slug']));if(false===strpos($preview,'faluss-link-card--empty'))return $preview;ob_start();?><article class="faluss-link-card faluss-link-card--align-center faluss-link-card--preview"><div class="faluss-link-card__body"><?php if((int)$p['avatar_attachment_id']): ?><div class="faluss-link-card__avatar"><?php echo wp_get_attachment_image((int)$p['avatar_attachment_id'],'medium',false,array('alt'=>'')); ?></div><?php endif; ?><h2 class="faluss-link-card__name"><?php echo esc_html($p['display_name']); ?></h2><p class="faluss-link-card__handle">@<?php echo esc_html($p['public_slug']); ?></p><?php if(''!==$p['bio']): ?><p class="faluss-link-card__bio"><?php echo esc_html($p['bio']); ?></p><?php endif; ?></div></article><?php return (string)ob_get_clean();}
 private static function link_notice(){$notice=isset($_GET['faluss_link_notice'])?sanitize_key(wp_unslash($_GET['faluss_link_notice'])):'';$messages=array('saved'=>__('Apparence enregistrée.','faluss-link'),'invalid'=>__('Nous ne pouvons pas enregistrer cette apparence.','faluss-link'));return isset($messages[$notice])?'<p class="faluss-link-editor__notice" role="status">'.esc_html($messages[$notice]).'</p>':'';}
 private static function owned_image($attachment_id,$user_id){$attachment=get_post((int)$attachment_id);return $attachment instanceof WP_Post&&(int)$attachment->post_author===(int)$user_id&&0===strpos((string)$attachment->post_mime_type,'image/');}
 private static function empty_card($m){return '<div class="faluss-link-card faluss-link-card--empty" role="status">'.esc_html($m).'</div>';}
}
