<?php
if(!defined('ABSPATH'))exit;
final class Faluss_Link {
 const STYLE='faluss-link-card'; const NETWORKS=array('instagram','tiktok','youtube','x','linkedin','github');
 public static function boot(){add_shortcode('faluss_link_card',array(__CLASS__,'card_shortcode'));add_shortcode('faluss_link_appearance',array(__CLASS__,'appearance_shortcode'));add_action('admin_post_faluss_link_save',array(__CLASS__,'save'));add_action('wp_enqueue_scripts',array(__CLASS__,'assets'));add_action('elementor/widgets/register',array(__CLASS__,'widgets'));}
 public static function activate(){return Faluss_Link_Schema::install();}
 public static function assets(){wp_register_style(self::STYLE,plugins_url('assets/css/faluss-link.css',FALUSS_LINK_FILE),array(),FALUSS_LINK_VERSION);}
 public static function card_shortcode($a=array()){return self::render_card((array)$a);}
 public static function appearance_shortcode(){return self::render_editor();}
 public static function render_card($a=array()){if(!self::identity_ready())return self::empty_card(__('Carte Faluss indisponible.','faluss-link'));$a=wp_parse_args($a,array('identifier'=>''));$slug=''!==$a['identifier']?sanitize_title($a['identifier']):(string)get_query_var('faluss_public_profile');$p=self::identity_profile($slug);if(null===$p)return self::empty_card(__('Cette carte Faluss n’est pas disponible.','faluss-link'));$pref=self::prefs($p['faluss_id']);if(!wp_style_is(self::STYLE,'registered'))self::assets();wp_enqueue_style(self::STYLE);$links=json_decode($p['external_links'],true);$social=self::socials($pref['social_links']);ob_start();?><article class="faluss-link-card faluss-link-card--<?php echo esc_attr($pref['link_style']); ?>" aria-label="<?php echo esc_attr($p['display_name']); ?>"><div class="faluss-link-card__cover"><?php if((int)$pref['cover_attachment_id']>0)echo wp_get_attachment_image((int)$pref['cover_attachment_id'],'large',false,array('alt'=>'')); ?></div><div class="faluss-link-card__body"><?php if(!empty($pref['available'])):?><span class="faluss-link-card__availability"><i></i><?php esc_html_e('Disponible','faluss-link'); ?></span><?php endif;?><?php if(!empty($pref['avatar_visible'])&&(int)$p['avatar_attachment_id']>0):?><div class="faluss-link-card__avatar"><?php echo wp_get_attachment_image((int)$p['avatar_attachment_id'],'medium',false,array('alt'=>'')); ?></div><?php endif;?><h1 class="faluss-link-card__name faluss-link-card__name--<?php echo esc_attr($pref['name_weight'].' '.$pref['name_treatment']); ?>"><?php echo esc_html($p['display_name']); ?></h1><?php if('announcement'===$pref['bio_mode']&&''!==$pref['announcement']):?><p class="faluss-link-card__announcement faluss-link-card__announcement--<?php echo esc_attr($pref['announcement_variant']); ?>"><?php echo esc_html($pref['announcement']); ?></p><?php elseif(''!==$p['bio']):?><p class="faluss-link-card__bio"><?php echo esc_html($p['bio']); ?></p><?php endif;?><?php if($social):?><nav class="faluss-link-card__social faluss-link-card__social--<?php echo esc_attr($pref['social_layout']); ?>" aria-label="<?php esc_attr_e('Réseaux sociaux','faluss-link'); ?>"><?php foreach($social as $s):?><a href="<?php echo esc_url($s['url']); ?>" target="_blank" rel="noopener noreferrer nofollow" aria-label="<?php echo esc_attr($s['network']); ?>"><?php echo self::icon($s['network']); ?></a><?php endforeach;?></nav><?php endif;?><?php foreach(is_array($links)?$links:array() as $l):if(!empty($l['url'])):?><a class="faluss-link-card__link" href="<?php echo esc_url($l['url']); ?>" target="_blank" rel="noopener noreferrer nofollow"><?php echo esc_html($l['label']??$l['url']); ?></a><?php endif;endforeach;?></div></article><?php return ob_get_clean();}
 public static function render_editor(){if(!is_user_logged_in()||!self::identity_ready())return self::empty_card(__('Connectez-vous pour personnaliser votre carte.','faluss-link'));$id=Faluss_Identity_Registry::get_active_for_wp_user(get_current_user_id());if(!$id)return self::empty_card(__('Votre identité Faluss est indisponible.','faluss-link'));$p=self::prefs($id);ob_start();?><section class="faluss-link-editor"><h2><?php esc_html_e('Apparence de ma carte Faluss','faluss-link'); ?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="faluss_link_save"><?php wp_nonce_field('faluss_link_save','faluss_link_nonce'); ?><label><?php esc_html_e('Photo de couverture (ID média)','faluss-link'); ?><input name="cover_attachment_id" type="number" value="<?php echo (int)$p['cover_attachment_id']; ?>"></label><label><input name="avatar_visible" type="checkbox" value="1" <?php checked($p['avatar_visible']); ?>> <?php esc_html_e('Afficher l’avatar','faluss-link'); ?></label><label><input name="available" type="checkbox" value="1" <?php checked($p['available']); ?>> <?php esc_html_e('Afficher Disponible','faluss-link'); ?></label><label><?php esc_html_e('Bio','faluss-link'); ?><select name="bio_mode"><option value="editorial" <?php selected($p['bio_mode'],'editorial'); ?>><?php esc_html_e('Texte éditorial','faluss-link'); ?></option><option value="announcement" <?php selected($p['bio_mode'],'announcement'); ?>><?php esc_html_e('Annonce','faluss-link'); ?></option></select></label><label><?php esc_html_e('Annonce','faluss-link'); ?><input name="announcement" maxlength="120" value="<?php echo esc_attr($p['announcement']); ?>"></label><label><?php esc_html_e('Réseaux (réseau|URL HTTPS, un par ligne)','faluss-link'); ?><textarea name="social_links"><?php foreach(self::socials($p['social_links']) as $s)echo esc_textarea($s['network'].'|'.$s['url'])."\n"; ?></textarea></label><button type="submit"><?php esc_html_e('Enregistrer','faluss-link'); ?></button></form></section><?php return ob_get_clean();}
 public static function save(){if(!is_user_logged_in()||!isset($_POST['faluss_link_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['faluss_link_nonce'])),'faluss_link_save'))wp_die('Accès refusé.');$id=Faluss_Identity_Registry::get_active_for_wp_user(get_current_user_id());if(!$id)wp_die('Identité indisponible.');global $wpdb;$t=Faluss_Link_Schema::table();$v=array('cover_attachment_id'=>max(0,(int)($_POST['cover_attachment_id']??0)),'avatar_visible'=>!empty($_POST['avatar_visible'])?1:0,'name_weight'=>'bold','name_treatment'=>'normal','available'=>!empty($_POST['available'])?1:0,'bio_mode'=>'announcement'===($_POST['bio_mode']??'')?'announcement':'editorial','announcement'=>sanitize_text_field(wp_unslash($_POST['announcement']??'')),'announcement_variant'=>'accent','social_links'=>wp_json_encode(self::socials(wp_unslash($_POST['social_links']??''))),'social_layout'=>'bubbles','link_style'=>'solid');$now=gmdate('Y-m-d H:i:s');$old=self::prefs($id);if($old['faluss_id']!==$id)$wpdb->query($wpdb->prepare('INSERT INTO `'.$t.'` (faluss_id,cover_attachment_id,avatar_visible,name_weight,name_treatment,available,bio_mode,announcement,announcement_variant,social_links,social_layout,link_style,created_at,updated_at) VALUES (%s,%d,%d,%s,%s,%d,%s,%s,%s,%s,%s,%s,%s,%s)',...array_merge(array($id),array_values($v),array($now,$now))));else $wpdb->update($t,$v+array('updated_at'=>$now),array('faluss_id'=>$id));wp_safe_redirect(wp_get_referer()?:home_url('/'));exit;}
 public static function widgets($m){if(!class_exists('Elementor\\Widget_Base')||!method_exists($m,'register'))return;require_once FALUSS_LINK_DIR.'includes/class-faluss-link-widgets.php';$m->register(new Faluss_Link_Card_Widget());$m->register(new Faluss_Link_Appearance_Widget());}
 private static function identity_ready(){return class_exists('Faluss_Identity_Schema')&&class_exists('Faluss_Identity_Registry')&&!empty(Faluss_Identity_Schema::get_status()['ready']);}
 private static function identity_profile($slug){global $wpdb;if(!is_string($slug)||''===$slug)return null;$t=Faluss_Identity_Schema::get_public_profiles_table();return $wpdb->get_row($wpdb->prepare('SELECT faluss_id,display_name,bio,avatar_attachment_id,external_links FROM `'.$t.'` WHERE public_slug=%s AND publication_status=%s',$slug,'published'),ARRAY_A);}
 private static function prefs($id){global $wpdb;$d=array('faluss_id'=>'','cover_attachment_id'=>0,'avatar_visible'=>1,'name_weight'=>'bold','name_treatment'=>'normal','available'=>0,'bio_mode'=>'editorial','announcement'=>'','announcement_variant'=>'accent','social_links'=>'[]','social_layout'=>'bubbles','link_style'=>'solid');$r=$wpdb->get_row($wpdb->prepare('SELECT * FROM `'.Faluss_Link_Schema::table().'` WHERE faluss_id=%s',$id),ARRAY_A);return is_array($r)?array_merge($d,$r):$d;}
 private static function socials($value){$in=is_string($value)?preg_split('/\r\n|\r|\n/',$value):json_decode((string)$value,true);$out=array();foreach((array)$in as $x){if(is_array($x)){$n=$x['network']??'';$u=$x['url']??'';}else{[$n,$u]=array_pad(explode('|',(string)$x,2),2,'');}$n=strtolower(trim($n));if(in_array($n,self::NETWORKS,true)&&filter_var($u,FILTER_VALIDATE_URL)&&'https'===strtolower(wp_parse_url($u)['scheme']??''))$out[]=array('network'=>$n,'url'=>$u);}return $out;}
 private static function icon($n){return '<svg aria-hidden="true" viewBox="0 0 24 24"><title>'.esc_html($n).'</title><circle cx="12" cy="12" r="10"/><path d="M8 12h8"/></svg>';}
 private static function empty_card($m){return '<div class="faluss-link-card faluss-link-card--empty" role="status">'.esc_html($m).'</div>';}
}
