<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Faluss_Identity_Client {
 const SETTINGS='faluss_identity_client_settings',COOKIE='faluss_identity_client_state',TTL=600,STYLE='faluss-identity-client-button';
 public static function register(){add_shortcode('faluss_identity_client_button',array(__CLASS__,'shortcode'));add_action('admin_post_nopriv_faluss_identity_client_start',array(__CLASS__,'start'));add_action('admin_post_faluss_identity_client_start',array(__CLASS__,'start'));add_action('template_redirect',array(__CLASS__,'callback'),0);add_action('init',array(__CLASS__,'rewrite'),20);add_filter('query_vars',fn($v)=>array_merge($v,array('faluss_identity_client_callback')));}
 public static function rewrite(){add_rewrite_rule('^faluss-identity/callback/?$','index.php?faluss_identity_client_callback=1','top');}
 public static function assets(){wp_register_style(self::STYLE,plugins_url('assets/css/faluss-identity-client.css',FALUSS_IDENTITY_CLIENT_FILE),array(),FALUSS_IDENTITY_CLIENT_VERSION);}
 public static function config(){return wp_parse_args((array)get_option(self::SETTINGS,array()),array('enabled'=>false,'authority'=>'https://faluss.me','client_id'=>'','return_urls'=>array()));}
 public static function enabled(){return !empty(self::config()['enabled']);}
 public static function shortcode($a=array()){return self::button((array)$a);}
 public static function button($a=array(),$inline=true){if(!self::enabled())return '';if(!wp_style_is(self::STYLE,'registered'))self::assets();wp_enqueue_style(self::STYLE);$a=wp_parse_args($a,array('label'=>__('Continuer avec Faluss','faluss-identity-client'),'redirect_url'=>home_url('/'),'accent_color'=>'#FF3D16','text_color'=>'#080808','surface_color'=>'#FFFFFF','radius'=>'999'));$redirect=self::allowed_return($a['redirect_url']);$style=$inline?' style="--fic-accent:'.esc_attr(self::hex($a['accent_color'],'#FF3D16')).';--fic-ink:'.esc_attr(self::hex($a['text_color'],'#080808')).';--fic-surface:'.esc_attr(self::hex($a['surface_color'],'#FFFFFF')).';--fic-radius:'.max(0,min(48,(int)$a['radius'])).'px;"':'';return '<div class="faluss-identity-client-button"'.$style.'><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="faluss_identity_client_start"><input type="hidden" name="redirect_to" value="'.esc_attr($redirect).'">'.wp_nonce_field('faluss_identity_client_start','faluss_identity_client_nonce',false,false).'<button class="faluss-identity-client-button__action" type="submit">'.esc_html($a['label']).'</button></form></div>';}
 public static function start(){if(!self::enabled()||!isset($_POST['faluss_identity_client_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['faluss_identity_client_nonce'])),'faluss_identity_client_start'))self::local_notice('invalid');$config=self::config();$redirect=self::allowed_return(isset($_POST['redirect_to'])?wp_unslash($_POST['redirect_to']):'');if(''===$config['client_id']||!self::authority($config['authority']))self::local_notice('invalid',$redirect);$mode=is_user_logged_in()?'link':'login';$uid='link'===$mode?get_current_user_id():null;try{$state=random_bytes(32);$verifier=random_bytes(32);$browser=random_bytes(32);}catch(Exception $e){self::local_notice('invalid',$redirect);}$hash=hash('sha256',$state);$bh=self::hmac($browser);if(null===$bh||!self::store_state($hash,$bh,$redirect,$mode,$uid))self::local_notice('invalid',$redirect);$cookie=self::b64($state.$verifier.$browser);setcookie(self::COOKIE,$cookie,self::cookie(time()+self::TTL));$_COOKIE[self::COOKIE]=$cookie;$q=array('response_type'=>'code','client_id'=>$config['client_id'],'redirect_uri'=>self::callback_uri(),'scope'=>'identity.basic identity.email','state'=>self::b64($state),'code_challenge'=>self::b64(hash('sha256',self::b64($verifier),true)),'code_challenge_method'=>'S256');wp_redirect(add_query_arg($q,rtrim($config['authority'],'/').'/oauth/authorize'),302,'Faluss Identity Client');exit;}
 public static function callback(){if('1'!==(string)get_query_var('faluss_identity_client_callback'))return;if(!self::enabled())self::local_notice('invalid');$state=isset($_GET['state'])&&is_string($_GET['state'])?wp_unslash($_GET['state']):'';$code=isset($_GET['code'])&&is_string($_GET['code'])?wp_unslash($_GET['code']):'';$row=self::consume_state($state);self::clear_cookie();if(null===$row||!self::opaque($code)){self::local_notice('invalid');}$claims=self::exchange($code,$row['verifier']);if(null===$claims)self::local_notice('invalid',$row['redirect_url']);$user=self::resolve_user($claims,$row);if(!$user instanceof WP_User)self::local_notice('link_required',$row['redirect_url']);wp_set_current_user($user->ID);wp_set_auth_cookie($user->ID,false,is_ssl());do_action('wp_login',$user->user_login,$user);self::local_notice('authenticated',$row['redirect_url']);}
 private static function consume_state($state){$raw=self::cookie_state();if(null===$raw||!self::opaque($state)||!hash_equals(self::b64($raw['state']),$state))return null;global $wpdb;$t=Faluss_Identity_Client_Schema::tables();$bh=self::hmac($raw['browser']);if(empty($t['states'])||null===$bh||false===$wpdb->query('START TRANSACTION'))return null;try{$r=$wpdb->get_row($wpdb->prepare('SELECT id,redirect_url,flow_mode,wp_user_id,expires_at,consumed_at FROM `'.$t['states'].'` WHERE state_hash=%s AND browser_hash=%s FOR UPDATE',hash('sha256',$raw['state']),$bh),ARRAY_A);if(!is_array($r)||null!==$r['consumed_at']||$r['expires_at']<=gmdate('Y-m-d H:i:s')||1!==$wpdb->query($wpdb->prepare('UPDATE `'.$t['states'].'` SET consumed_at=%s WHERE id=%d AND consumed_at IS NULL',gmdate('Y-m-d H:i:s'),$r['id']))||false===$wpdb->query('COMMIT')){$wpdb->query('ROLLBACK');return null;}$r['verifier']=self::b64($raw['verifier']);return $r;}catch(Exception $e){$wpdb->query('ROLLBACK');return null;}}
 private static function exchange($code,$verifier){$c=self::config();$body=array('grant_type'=>'authorization_code','client_id'=>$c['client_id'],'redirect_uri'=>self::callback_uri(),'code'=>$code,'code_verifier'=>$verifier);$secret=defined('FALUSS_IDENTITY_CLIENT_SECRET')?constant('FALUSS_IDENTITY_CLIENT_SECRET'):'';if(is_string($secret)&&''!==$secret)$body['client_secret']=$secret;$r=wp_remote_post(rtrim($c['authority'],'/').'/oauth/token',array('timeout'=>15,'redirection'=>0,'headers'=>array('Accept'=>'application/json'),'body'=>$body));if(is_wp_error($r)||200!==(int)wp_remote_retrieve_response_code($r))return null;$d=json_decode(wp_remote_retrieve_body($r),true);if(!is_array($d)||!self::uuid($d['faluss_id']??'')||false===strpos(' '.($d['scope']??'').' ',' identity.basic '))return null;if(isset($d['email'])&&!is_email($d['email']))return null;return $d;}
 private static function resolve_user($c,$state){global $wpdb;$t=Faluss_Identity_Client_Schema::tables();$linked=$wpdb->get_var($wpdb->prepare('SELECT wp_user_id FROM `'.$t['links'].'` WHERE faluss_id=%s',$c['faluss_id']));if('link'===$state['flow_mode']){if($linked||!is_user_logged_in()||(int)$state['wp_user_id']!==get_current_user_id())return null;return self::link((int)$state['wp_user_id'],$c['faluss_id'])?get_user_by('id',(int)$state['wp_user_id']):null;}if($linked){$u=get_user_by('id',(int)$linked);return $u instanceof WP_User?$u:null;}if(empty($c['email']))return null;$existing=get_user_by('email',$c['email']);if($existing instanceof WP_User)return null;if(!get_role('subscriber') instanceof WP_Role)return null;try{$id=wp_insert_user(array('user_login'=>'faluss_'.bin2hex(random_bytes(10)),'user_pass'=>bin2hex(random_bytes(32)),'user_email'=>$c['email'],'role'=>'subscriber'));}catch(Exception $e){return null;}if(is_wp_error($id))return null;return self::link((int)$id,$c['faluss_id'])?get_user_by('id',(int)$id):null;}
 private static function link($uid,$fid){global $wpdb;$t=Faluss_Identity_Client_Schema::tables();if(false===$wpdb->query('START TRANSACTION'))return false;try{$a=$wpdb->get_var($wpdb->prepare('SELECT id FROM `'.$t['links'].'` WHERE wp_user_id=%d OR faluss_id=%s FOR UPDATE',$uid,$fid));if($a||1!==$wpdb->query($wpdb->prepare('INSERT INTO `'.$t['links'].'` (wp_user_id,faluss_id,created_at,last_proved_at) VALUES (%d,%s,%s,%s)',$uid,$fid,gmdate('Y-m-d H:i:s'),gmdate('Y-m-d H:i:s')))||false===$wpdb->query('COMMIT')){$wpdb->query('ROLLBACK');return false;}return true;}catch(Exception $e){$wpdb->query('ROLLBACK');return false;}}
 private static function store_state($sh,$bh,$url,$mode,$uid){global $wpdb;$t=Faluss_Identity_Client_Schema::tables();return !empty($t['states'])&&1===$wpdb->query($wpdb->prepare('INSERT INTO `'.$t['states'].'` (state_hash,browser_hash,redirect_url,flow_mode,wp_user_id,expires_at,created_at) VALUES (%s,%s,%s,%s,%d,%s,%s)',$sh,$bh,$url,$mode,$uid,gmdate('Y-m-d H:i:s',time()+self::TTL),gmdate('Y-m-d H:i:s')));}
 private static function cookie_state(){if(empty($_COOKIE[self::COOKIE])||!is_string($_COOKIE[self::COOKIE]))return null;$r=base64_decode(strtr($_COOKIE[self::COOKIE],'-_','+/').str_repeat('=',(4-strlen($_COOKIE[self::COOKIE])%4)%4),true);return is_string($r)&&96===strlen($r)?array('state'=>substr($r,0,32),'verifier'=>substr($r,32,32),'browser'=>substr($r,64,32)):null;}
 private static function allowed_return($url){$home=home_url('/');$urls=array_unique(array_merge(array($home),(array)self::config()['return_urls']));return is_string($url)&&in_array($url,$urls,true)&&self::local($url)?$url:$home;} private static function local($u){$a=wp_parse_url($u);$b=wp_parse_url(home_url('/'));return is_array($a)&&is_array($b)&&isset($a['scheme'],$a['host'])&&!isset($a['user'],$a['pass'])&&0===strcasecmp($a['scheme'],$b['scheme'])&&0===strcasecmp($a['host'],$b['host']);} private static function authority($u){return 'https://faluss.me'===rtrim((string)$u,'/');} private static function callback_uri(){return home_url('/faluss-identity/callback');} private static function hmac($v){return function_exists('wp_salt')?hash_hmac('sha256',$v,wp_salt('faluss_identity_client_state')):null;} private static function b64($v){return rtrim(strtr(base64_encode($v),'+/','-_'),'=');} private static function opaque($v){return is_string($v)&&1===preg_match('/^[A-Za-z0-9_-]{43}$/D',$v);} private static function uuid($v){return is_string($v)&&1===preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$v);} private static function hex($v,$f){return is_string($v)&&1===preg_match('/^#[A-Fa-f0-9]{6}$/D',$v)?$v:$f;} private static function cookie($e){return array('expires'=>$e,'path'=>'/','domain'=>defined('COOKIE_DOMAIN')?COOKIE_DOMAIN:'','secure'=>true,'httponly'=>true,'samesite'=>'Lax');} private static function clear_cookie(){setcookie(self::COOKIE,'',self::cookie(time()-3600));unset($_COOKIE[self::COOKIE]);} private static function local_notice($n='invalid',$u=null){wp_safe_redirect(add_query_arg('faluss_identity_client_notice',sanitize_key($n),self::allowed_return($u)));exit;}
 public static function callback_url(){return self::callback_uri();}
}
