<?php
if(!defined('ABSPATH'))exit;
final class Faluss_Identity_Client_Elementor_Widget extends \Elementor\Widget_Base {
 public function get_name(){return 'faluss_identity_client_button';} public function get_title(){return 'Continuer avec Faluss';} public function get_icon(){return 'eicon-lock-user';} public function get_categories(){return array('general');}
 protected function register_controls(){
  $this->start_controls_section('content',array('label'=>'Contenu'));$this->add_control('label',array('label'=>'Libellé','type'=>\Elementor\Controls_Manager::TEXT,'default'=>'Continuer avec Faluss'));$this->add_control('redirect_url',array('label'=>'Retour local','type'=>\Elementor\Controls_Manager::URL));$this->end_controls_section();
  $this->start_controls_section('style',array('label'=>'Style','tab'=>\Elementor\Controls_Manager::TAB_STYLE));$this->start_controls_tabs('states');$this->start_controls_tab('normal',array('label'=>'Normal'));$this->add_control('text_color',array('label'=>'Texte','type'=>\Elementor\Controls_Manager::COLOR,'default'=>'#FFFFFF','selectors'=>array('{{WRAPPER}} .faluss-identity-client-button__action'=>'color: {{VALUE}};')));$this->add_control('background_color',array('label'=>'Fond','type'=>\Elementor\Controls_Manager::COLOR,'default'=>'#FF3D16','selectors'=>array('{{WRAPPER}} .faluss-identity-client-button__action'=>'background-color: {{VALUE}}; border-color: {{VALUE}};')));$this->end_controls_tab();$this->start_controls_tab('hover',array('label'=>'Survol'));$this->add_control('hover_text_color',array('label'=>'Texte','type'=>\Elementor\Controls_Manager::COLOR,'selectors'=>array('{{WRAPPER}} .faluss-identity-client-button__action:hover'=>'color: {{VALUE}};')));$this->add_control('hover_background',array('label'=>'Fond','type'=>\Elementor\Controls_Manager::COLOR,'selectors'=>array('{{WRAPPER}} .faluss-identity-client-button__action:hover'=>'background-color: {{VALUE}}; border-color: {{VALUE}};')));$this->end_controls_tab();$this->end_controls_tabs();
  $this->add_group_control(\Elementor\Group_Control_Typography::get_type(),array('name'=>'typography','selector'=>'{{WRAPPER}} .faluss-identity-client-button__action'));$this->add_group_control(\Elementor\Group_Control_Border::get_type(),array('name'=>'border','selector'=>'{{WRAPPER}} .faluss-identity-client-button__action'));$this->add_control('radius',array('label'=>'Arrondi','type'=>\Elementor\Controls_Manager::DIMENSIONS,'selectors'=>array('{{WRAPPER}} .faluss-identity-client-button__action'=>'border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};')));$this->add_group_control(\Elementor\Group_Control_Box_Shadow::get_type(),array('name'=>'shadow','selector'=>'{{WRAPPER}} .faluss-identity-client-button__action'));$this->end_controls_section();
 }
 protected function render(){ $s=$this->get_settings_for_display(); echo Faluss_Identity_Client::button(array('label'=>$s['label'],'redirect_url'=>isset($s['redirect_url']['url'])?$s['redirect_url']['url']:''),false); }
}
