<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Faluss_Identity_Client_Schema {
 const VERSION='1'; const OPTION='faluss_identity_client_schema_version'; const LOCK_TIMEOUT=10;
 public static function schema(){return array('links'=>array('suffix'=>'faluss_identity_links','columns'=>array('id'=>array('type'=>'bigint(20) unsigned','null'=>false,'auto'=>true),'wp_user_id'=>array('type'=>'bigint(20) unsigned','null'=>false),'faluss_id'=>array('type'=>'char(36)','null'=>false),'created_at'=>array('type'=>'datetime','null'=>false),'last_proved_at'=>array('type'=>'datetime','null'=>false)),'indexes'=>array('PRIMARY'=>array(true,array('id')),'wp_user_id_unique'=>array(true,array('wp_user_id')),'faluss_id_unique'=>array(true,array('faluss_id')))),'states'=>array('suffix'=>'faluss_identity_client_state','columns'=>array('id'=>array('type'=>'bigint(20) unsigned','null'=>false,'auto'=>true),'state_hash'=>array('type'=>'char(64)','null'=>false),'browser_hash'=>array('type'=>'char(64)','null'=>false),'redirect_url'=>array('type'=>'varchar(2048)','null'=>false),'flow_mode'=>array('type'=>'varchar(20)','null'=>false),'wp_user_id'=>array('type'=>'bigint(20) unsigned','null'=>true),'expires_at'=>array('type'=>'datetime','null'=>false),'consumed_at'=>array('type'=>'datetime','null'=>true),'created_at'=>array('type'=>'datetime','null'=>false)),'indexes'=>array('PRIMARY'=>array(true,array('id')),'state_hash_unique'=>array(true,array('state_hash')),'expires_at'=>array(false,array('expires_at')))) );}
 public static function tables(){global $wpdb;$out=array();if(!is_object($wpdb)||empty($wpdb->prefix)||1!==preg_match('/^[A-Za-z0-9_]+$/',$wpdb->prefix))return $out;foreach(self::schema() as $k=>$d)$out[$k]=$wpdb->prefix.$d['suffix'];return $out;}
 public static function install_or_verify(){global $wpdb;if(!is_object($wpdb)||!method_exists($wpdb,'get_var')||!method_exists($wpdb,'get_charset_collate'))return false;$tables=self::tables();if(count($tables)!==2)return false;$found=0;foreach($tables as $table){$present=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table));if(null===$present&&!empty($wpdb->last_error))return false;if($table===$present)$found++;}if(0<$found&&2>$found)return false;if(2===$found){if(!self::verify_all($tables))return false;update_option(self::OPTION,self::VERSION,false);return true;}$lock='faluss_identity_client_'.substr(hash('sha256',$wpdb->prefix),0,32);if(1!==(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,%d)',$lock,self::LOCK_TIMEOUT)))return false;try{foreach($tables as $table){if($table===$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table)))return false;}foreach(self::schema() as $k=>$d){if(false===$wpdb->query(self::create($tables[$k],$d,$wpdb->get_charset_collate())))return false;}if(!self::verify_all($tables))return false;update_option(self::OPTION,self::VERSION,false);return true;}finally{$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}}
 private static function verify_all($tables){foreach(self::schema() as $k=>$d)if(!self::verify($tables[$k],$d))return false;return true;}
 private static function verify($table,$def){global $wpdb;$status=$wpdb->get_row($wpdb->prepare('SHOW TABLE STATUS LIKE %s',$table),ARRAY_A);if(!is_array($status)||0!==strcasecmp('InnoDB',$status['Engine']??''))return false;$cols=$wpdb->get_results('SHOW FULL COLUMNS FROM `'.$table.'`',ARRAY_A);if(!is_array($cols)||count($cols)!==count($def['columns']))return false;$actual=array();foreach($cols as $c)$actual[$c['Field']]=$c;foreach($def['columns'] as $n=>$want){if(!isset($actual[$n])||strtolower($actual[$n]['Type'])!==$want['type']||('YES'===$actual[$n]['Null'])!==$want['null']||(!empty($want['auto'])!==(false!==strpos(strtolower($actual[$n]['Extra']??''),'auto_increment'))))return false;}$rows=$wpdb->get_results('SHOW INDEX FROM `'.$table.'`',ARRAY_A);$indexes=array();foreach((array)$rows as $r){$name=$r['Key_name'];if(!isset($indexes[$name]))$indexes[$name]=array('unique'=>'0'===(string)$r['Non_unique'],'cols'=>array());$indexes[$name]['cols'][(int)$r['Seq_in_index']]=$r['Column_name'];}if(count($indexes)!==count($def['indexes']))return false;foreach($def['indexes'] as $name=>$want){if(!isset($indexes[$name]))return false;ksort($indexes[$name]['cols']);if($indexes[$name]['unique']!==$want[0]||array_values($indexes[$name]['cols'])!==$want[1])return false;}return true;}
 private static function create($table,$def,$collate){$lines=array();foreach($def['columns'] as $n=>$c)$lines[]='`'.$n.'` '.$c['type'].($c['null']?' NULL':' NOT NULL').(!empty($c['auto'])?' AUTO_INCREMENT':'');foreach($def['indexes'] as $n=>$i){$cols='`'.implode('`, `',$i[1]).'`';$lines[]='PRIMARY'===$n?'PRIMARY KEY ('.$cols.')':($i[0]?'UNIQUE KEY `'.$n.'` ('.$cols.')':'KEY `'.$n.'` ('.$cols.')');}return 'CREATE TABLE `'.$table.'` ('.implode(', ',$lines).') ENGINE=InnoDB '.$collate;}
}
